### ISSUE TITLE
What strategy of sinlge-spa-vue replace DomEl or append it?

### ISSUE THREAD

**Issue by guguji5** [single-spa/single-spa-vue#39]
I create a sample using the single-spa-vue, when the activity function is called, it sometimes append the application to the DomEl, and then sometimes replace it. it is puzzled.

the online sample address is http://116.85.27.118:9090/. the code repo is https://github.com/guguji5/single-spa-sample

When we go the "app1" page from the menu, the content of app1 is appended to the dom#content. and then we go to "app2" page, the dom is replaced by app2. both app1 and app2 are using the same DomEl (`el:"#content"`) to mount.

Could anybody help to see what happened?

**Comment by joeldenning** [comment]
Some notes:

1. Prefer `<router-link>` instead of `<a>` for navigation - see https://router.vuejs.org/api/#router-link.
2. Do not put `<a>` or any other DOM elements into root-config. Instead, use Vue to create the HTML.
3. If possible, choose either history mode or hash mode. Do not use both, unless you have to.
4. Use a separate DOM element container for each single-spa application. Do not share the same `#content` dom element. Each single-spa application should have its own DOM element container.
5. Use CSS for layout of your menu. Use `position: fixed` on the menu, and `margin-left: 184px` on your content wrappers.

I have created https://github.com/guguji5/single-spa-sample/pull/1 which does some of these things. However it does not do all of them - you should read through the list and try to incorporate as many of them as possible.

**Comment by guguji5** [comment]
Thank you very much for your warm and patient guidance
