### ISSUE TITLE
Does this project support hash mode?

### ISSUE THREAD

**Issue by hui-fly** [single-spa/single-spa-vue#44]
I used the hash mode but it didn't take effect and the route did not jump normally

**Comment by joeldenning** [comment]
Yes, both single-spa and single-spa-vue support hash mode. I am very confident that this works correctly with single-spa, but have not tried it with single-spa-vue. However, it should work.

Could you please provide a repo that demonstrates the problem?

**Comment by blacklisten** [comment]
I use `single-spa-vue@1.5.2`，but used the hash mode but it didn't take effect and I observed that `router-view` is not loaded correctly.  Cause the route cannot jump normally.  used history mode is a success.  [demo](https://github.com/blacklisten/single-spa-demo/tree/dev-vue-ts) @joeldenning

**Comment by joeldenning** [comment]
Thanks for the repository that demonstrates the problem. The bug was in using `location.pathname` instead of `location.hash`. See https://github.com/blacklisten/single-spa-demo/pull/1 which shows the fix. For more information, see the following links:

- https://developer.mozilla.org/en-US/docs/Web/API/Location
- https://developer.mozilla.org/en-US/docs/Web/API/Location/hash
- https://developer.mozilla.org/en-US/docs/Web/API/Location/pathname
