### ISSUE TITLE
question: How to mount application to another main application correctly

### ISSUE THREAD

**Issue by jawn-ha** [single-spa/single-spa-vue#47]
Hi!  what you are developing here is great! 
I have two vue applications named 'Layout' and 'app2' and the 'Layout' is activied at all time. I use singe-spa-vue 'el' option to make 'app2' mounted the specified dom node of 'Layout'. It's everthing ok when I first click into 'app2' but when I refresh page it's wrong for something because 'Layout' also refresh and 'app2' cannot find the dom node
I don’t know How to fix it.
My English is not very good. I hope you can understand my problem
![image](https://user-images.githubusercontent.com/16000122/85990214-435d5300-ba24-11ea-822a-7e98ab8eefcb.png)
 It's everthing ok when I first click into 'app2'
![image](https://user-images.githubusercontent.com/16000122/85990550-ca123000-ba24-11ea-9fa7-14fa07464d36.png)
when I refresh page
![image](https://user-images.githubusercontent.com/16000122/85991075-80761500-ba25-11ea-8466-2fcc3200d78f.png)

**Comment by filoxo** [comment]
> I use singe-spa-vue 'el' option to make 'app2' mounted the specified dom node of 'Layout'.

This is the problem. By trying to mount app2 inside of Layout you are creating a dependency where Layout must be loaded and mounted before app2. Single-spa simply tries mounting the applications as soon as they have been dowloaded. We do not encourage this strategy because of that. You should try to find a way to make Layout and app2 sibling elements instead. That would avoid this issue entirely. This is ideal because then you do not need to create that rendering dependency and the applications can remain much more independent. Definitely try to achieve this first, it will be the best solution in the long run. 

But I realize that this is not always possible so you could also consider using JavaScript imports instead. This would mean that in Layout, it will need its own routing config, import the component you need (eg. `import App2 from '@your-org/app2'`), and add a route config that renders that component when a location matches. This is kind of duplicating the work of single-spa, and is limited to only one framework but its an option.

**Comment by joeldenning** [comment]
Thanks Carlos, you are completely right. One thing I'll add is that we created [single-spa-layout](https://single-spa.js.org/docs/layout-overview) as an official way to support laying out your microfrontends. It is currently in beta and we'd appreciate any feedback you have on it if you try it out. With single-spa-layout, you no longer use the `el` option in single-spa-vue, but instead define the layout centrally in your root config.

**Comment by filoxo** [comment]
This issue provides a sufficient answer so I'm going to close.
