### ISSUE TITLE
PR offer: move to Typescript in leu of Vue 3 release

### ISSUE THREAD

**Issue by vegerot** [single-spa/single-spa-vue#56]
Vue 3 is moving from Flow to Typescript, and maybe `single-spa-vue` should too.

I say "PR offer" because I'd be willing to work on this if this is something you want.

**Comment by joeldenning** [comment]
I use typescript in some projects and enjoy it, but am a bit hesitant about this. The main concerns are that I haven't seen you contribute to single-spa-vue before and don't see many benefits of refactoring this project to typescript.

I think there's a difference between a maintainer proposing changing programming languages versus a first-time contributor. The following tweet comes to mind: https://twitter.com/_developit/status/1251176832424181762

As far as I know, rewriting to typescript doesn't provide any benefits to the consumers of this library, since we already have `"types"` in the package.json.  Any benefits would only be for maintainers of single-spa-vue and any future contributors, although one could argue that requiring typescript knowledge increases the barrier to entry for new contributors. Also, "Vue is written in typescript" isn't a very compelling reason for me to refactor single-spa-vue.

There are other changes to this library that I think would provide more benefit that I could point you to, if you'd like to help out with them. One in particular is to standardize the domElementGetter logic across single-spa-vue, single-spa-react, single-spa-angular, etc by publishing an npm library that contains the logic.

**Comment by vegerot** [comment]
Thanks for the quick response!  I see your types.  The reason I personally would like it to be written in typescript is that it makes the main file easier to read.

Today I started looking into single-spa, and I had a question about what the `singleSpaVue` function did, so I pressed goto definition in my editor (I use vim btw /meme) and it took me to a `.d.ts` file that didn't tell me at all how it worked.  So I went to this GitHub repo and looked at the code here.  But it was harder to follow what was going on without strict interfaces.  So I had to have the .d.ts file opened in one half of my screen and the code in another, which was not ideal either.

That's a really interesting tweet you linked; I hadn't seen that before, thanks!  One response that I like is one [asking about jsdoc](https://twitter.com/sreechandan98/status/1251239467249094657).  You say that you don't want to increase the barrier of entry for contributors, but if you also want to put solid standards for type coverage in you code (either through .d.ts, jsdoc, or typescript), then anybody who wants to add a function or class to this library will be required to document their contribution.

Speaking of asking for better jsdoc coverage, I found the precision of the .d.ts file lackluster.  Many of the types in there are either so broad that they're unhelpful for people trying to get an understanding of the codebase (like the `SingleSpaVueLifecycles`), or nearly wrong (like `SingleSpaVueOpts.appOptions` says it's optional and any, but https://github.com/single-spa/single-spa-vue/blob/main/src/single-spa-vue.js#L27 places requirements both on that it's required and some of the subtypes).

I would be okay with either contributing details to the .d.ts or adding jsdoc, I'm not a TypeScript evangelist.  But one reason I like typescript here is that with its powerful type inference capabilities, many of the manual labor that would need to be done with .d.ts or jsdoc can be done automatically.  For example, instead of having `SingleSpaVueLifecycles` all return `Promise<any>`, Typescript could infer that `mount` returns `Promise<typeof instance.vueInstance>` (which could be further inferred to be `Promise<Vue | Element>` if we added it as a dev dependency, which is a separate controversial idea for sure that I may not advocate for) for less effort than it took to write that .d.ts interface in the first place.

Anyways, thanks so much for taking the time to read this!  And as we evaluate whether to use single-spa in our product and begin integrating it, expect to see more issues and PRs (not type related!) to come. 

Thank you

**Comment by joeldenning** [comment]
I appreciate the explanation, but am not persuaded. Having someone who had never heard of the project until today rewrite/refactor the code and build process causes me more work in reviewing the proposed change than it does in value to the users of the library.

If you'd like to contribute to the declaration file and/or jsdocs, I'd gladly review a PR.
